# Generated by Django 2.2.1 on 2019-05-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=200)),
                ('project_content', models.TextField()),
                ('project_published', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
