# Generated by Django 2.2.1 on 2019-05-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190511_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_published',
        ),
        migrations.AddField(
            model_name='project',
            name='project_description',
            field=models.TextField(default=''),
        ),
    ]
